# WandB Sweep configuration
# Run `wandb sweep sweep_config.yaml`
# Will return <SWEEP_ID>
# Run `wandb agent <SWEEP_ID>`
project: climate-peft
name: MaxSeq HP Search
program: finetune.py
method: random
metric:
  name: val_loss
  goal: minimize
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - --project
  - climate-peft
parameters:
  # max_seq:
  #   values: [1024, 2048, 3072]
  alpha:
    values: [6, 18, 32, 64, 128]
  rank:
    values: [6, 18, 32, 64, 128]